---
title: "Order Steps"
output: 
    learnr::tutorial:
        allow_skip: true
        theme: cerulean
        self_contained: true
runtime: shiny_prerendered
---



```{r 01-setup, include=FALSE}
library(learnr)
library(sortable)
knitr::opts_chunk$set(echo = FALSE)
```


## Research process


```{r research-process}
# Define the answer options
rs <- c(
    "Ask a research question.",
    "Design a study to collect data that can answer the question.",
    "Carry out the study and collect the data.",
    "Apply statistical analysis to picture and describe the data, and provide a basis for drawing conclusions.",
    "Draw conclusions about what the data tell us in answer to our original question.",
    "Interpret the results, give a critical discussion of the whole study, and prepare a report."
  )


# Initialize the question
question_rank(
  "**Order the steps of the research process.**",
  answer(rs, correct = TRUE),

  # answer(rev(rs), correct = FALSE, message = "Other direction!"),
  # answer(c(rs[2],rs[1],rs[3],rs[4],rs[5],rs[6]), correct = FALSE, message = "1 + 2 vertauscht"),
  # answer(c(rs[1],rs[3],rs[2],rs[4],rs[5],rs[6]), correct = FALSE, message = "2 + 3 vertauscht"),
  # answer(c(rs[1],rs[2],rs[4],rs[3],rs[5],rs[6]), correct = FALSE, message = "3 + 4 vertauscht"),
  # answer(c(rs[1],rs[2],rs[3],rs[5],rs[4],rs[6]), correct = FALSE, message = "4 + 5 vertauscht"),
  # answer(c(rs[1],rs[2],rs[3],rs[4],rs[6],rs[5]), correct = FALSE, message = "5 + 6 vertauscht"),

  allow_retry = TRUE
)
```


## Estimation Plan

```{r estimation-plan}
# Define the answer options
estimation_steps <- c(
    "State the research question. Express it as a “how much” or “to what extent” question.",
    "Identify the measure that’s most appropriate for answering that question.",
    "Design a study that uses an appropriate measure and gives you good point and interval estimates to answer your question.",
    "Carry out the study and collect the data.",
    "Examine the data, calculate point and interval estimates, and make a figure.",
    "Interpret the results, using judgment in the research context",
    "Report the study, making sure to state there was no selective reporting of just some of the results, and giving full details of every aspect of the study.",
    "Adopt meta-analytic thinking throughout. Seek other similar studies and, if appropriate, conduct a meta-analysis.",
    "Consider conducting a replication."
  )


# Initialize the question
question_rank(
  "**Order the steps for a more elaborated research process using the estimation approach.**",
  answer(estimation_steps, correct = TRUE),
  answer(rev(estimation_steps), correct = FALSE, message = "Other direction!"),
  allow_retry = TRUE
)
```

